DROP TABLE IF EXISTS items CASCADE;
CREATE TABLE items (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  title  VARCHAR(255) NOT NULL,
  is_complete BOOLEAN DEFAULT false,
  category_id INTEGER REFERENCES categories(id) ON DELETE CASCADE
);
